"""
Core data models for LLM Orchestrator.

This file defines the fundamental data structures (schemas) used throughout
the orchestrator. Think of these as the "contracts" or "blueprints" that
ensure all parts of the system speak the same language.

Why this file exists:
- Type safety: Catch errors at development time, not runtime
- Documentation: Data structures are self-documenting
- Validation: Ensure data is correct before processing
- Consistency: Everyone uses the same data format
"""

from dataclasses import dataclass, field
from typing import Optional, Dict, Any, List
from datetime import datetime
from enum import Enum
import uuid


# ══════════════════════════════════════════════════════════════════════════
# ENUMS - Constrained choices for specific fields
# ══════════════════════════════════════════════════════════════════════════

class RequestPriority(str, Enum):
    """
    Priority level for LLM requests.

    Determines how urgently a request needs to be processed:
    - LOW: Batch processing, can wait (e.g., background analysis)
    - MEDIUM: Normal priority (most user requests)
    - HIGH: Interactive user queries that need fast response
    - CRITICAL: System-critical operations that must succeed immediately
    """
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ProviderStatus(str, Enum):
    """
    Current operational status of a provider.

    - HEALTHY: Provider is working normally
    - DEGRADED: Provider is slow or having issues, but still usable
    - UNHEALTHY: Provider is failing, don't use it
    - CIRCUIT_OPEN: Circuit breaker is active, provider is temporarily disabled
    """
    HEALTHY = "healthy"
    DEGRADED = "degraded"
    UNHEALTHY = "unhealthy"
    CIRCUIT_OPEN = "circuit_open"


class TaskComplexity(str, Enum):
    """
    Task complexity levels for intelligent routing.

    - SIMPLE: Basic queries, definitions (use cheap models)
    - MODERATE: Standard questions (use balanced models)
    - COMPLEX: Analysis, reasoning (use powerful models)
    - VERY_COMPLEX: Deep analysis, multi-step (use best models)
    """
    SIMPLE = "simple"
    MODERATE = "moderate"
    COMPLEX = "complex"
    VERY_COMPLEX = "very_complex"


# ══════════════════════════════════════════════════════════════════════════
# REQUEST MODELS - What you send to the orchestrator
# ══════════════════════════════════════════════════════════════════════════

@dataclass
class LLMRequest:
    """
    A request to generate text using an LLM.

    This is what you send to the orchestrator when you want an AI response.

    Attributes:
        prompt: The input text/question for the LLM
        max_tokens: Maximum length of response (prevents runaway costs)
        temperature: Randomness (0.0 = deterministic, 1.0 = creative)
        system_prompt: Instructions that guide the LLM's behavior
        priority: How urgent this request is
        metadata: Any additional context (user_id, session_id, etc.)

    Example:
        request = LLMRequest(
            prompt="Explain quantum physics in simple terms",
            max_tokens=500,
            temperature=0.7,
            priority=RequestPriority.MEDIUM
        )
    """

    # Required fields
    prompt: str

    # Optional parameters with sensible defaults
    max_tokens: int = 1000
    temperature: float = 0.7
    system_prompt: Optional[str] = None
    priority: RequestPriority = RequestPriority.MEDIUM

    # Metadata for tracking and routing
    metadata: Dict[str, Any] = field(default_factory=dict)
    request_id: str = field(default_factory=lambda: f"req_{uuid.uuid4().hex}")

    def __post_init__(self):
        """Validate request after creation"""
        if not self.prompt or not self.prompt.strip():
            raise ValueError("Prompt cannot be empty")

        if self.max_tokens < 1:
            raise ValueError("max_tokens must be at least 1")

        if not (0.0 <= self.temperature <= 2.0):
            raise ValueError("temperature must be between 0.0 and 2.0")


# ══════════════════════════════════════════════════════════════════════════
# RESPONSE MODELS - What the orchestrator returns to you
# ══════════════════════════════════════════════════════════════════════════

@dataclass
class LLMResponse:
    """
    The response from an LLM request.

    Contains the generated text plus metadata about the request.

    Attributes:
        content: The actual text generated by the LLM
        provider: Which provider generated this (e.g., "anthropic", "openai")
        model: Which model was used (e.g., "claude-sonnet-4", "gpt-4o")
        request_id: Links back to the original request
        success: Whether the request succeeded
        error_message: If failed, what went wrong
        usage: Token counts and costs
        latency_ms: How long it took (milliseconds)
        cached: Whether this was served from cache

    Example:
        response = LLMResponse(
            content="Quantum physics is the study of...",
            provider="anthropic",
            model="claude-sonnet-4",
            success=True,
            latency_ms=1250
        )
    """

    # Response data
    content: str
    provider: str
    model: str

    # Request tracking
    request_id: str

    # Status
    success: bool = True
    error_message: Optional[str] = None

    # Usage metrics
    usage: Optional[Dict[str, Any]] = None  # tokens, cost, etc.
    latency_ms: float = 0.0
    raw_response: Optional[Dict[str, Any]] = None

    # Optimization metadata
    cached: bool = False
    fallback_used: bool = False
    attempted_providers: List[str] = field(default_factory=list)

    # Timestamp
    timestamp: datetime = field(default_factory=datetime.now)


# ══════════════════════════════════════════════════════════════════════════
# PROVIDER MODELS - Information about LLM providers
# ══════════════════════════════════════════════════════════════════════════

@dataclass
class ProviderMetrics:
    """
    Real-time metrics for a provider.

    Tracks performance and health to make smart routing decisions.

    Attributes:
        provider_name: Name of the provider (e.g., "anthropic")
        status: Current health status
        success_rate: Percentage of successful requests (0.0-1.0)
        avg_latency_ms: Average response time
        error_count: Number of recent errors
        total_requests: Total requests processed
        last_success: When last successful request completed
        last_error: When last error occurred

    Usage:
        The orchestrator uses these metrics to decide:
        - Should I use this provider? (status check)
        - Which provider is fastest? (avg_latency_ms)
        - Which provider is most reliable? (success_rate)
    """

    provider_name: str
    status: ProviderStatus = ProviderStatus.HEALTHY

    # Performance metrics
    success_rate: float = 1.0  # 1.0 = 100% success
    avg_latency_ms: float = 0.0

    # Error tracking
    error_count: int = 0
    total_requests: int = 0

    # Timestamps
    last_success: Optional[datetime] = None
    last_error: Optional[datetime] = None

    def is_healthy(self) -> bool:
        """Check if provider is healthy enough to use"""
        return self.status in [ProviderStatus.HEALTHY, ProviderStatus.DEGRADED]

    def update_success(self, latency_ms: float):
        """Record a successful request"""
        self.total_requests += 1
        self.last_success = datetime.now()

        # Update rolling average latency
        if self.total_requests == 1:
            self.avg_latency_ms = latency_ms
        else:
            # Weighted average: 80% old, 20% new
            self.avg_latency_ms = (0.8 * self.avg_latency_ms) + (0.2 * latency_ms)

        # Update success rate
        successful_requests = self.total_requests - self.error_count
        self.success_rate = successful_requests / self.total_requests

    def update_error(self):
        """Record a failed request"""
        self.total_requests += 1
        self.error_count += 1
        self.last_error = datetime.now()

        # Update success rate
        successful_requests = self.total_requests - self.error_count
        self.success_rate = successful_requests / self.total_requests if self.total_requests > 0 else 0.0


# ══════════════════════════════════════════════════════════════════════════
# ROUTING MODELS - How to select providers
# ══════════════════════════════════════════════════════════════════════════

@dataclass
class RoutingContext:
    """
    Context information for making routing decisions.

    Contains everything the router needs to pick the best provider.

    Attributes:
        request: The original LLM request
        available_providers: Which providers are currently usable
        provider_metrics: Current metrics for each provider
        constraints: User-specified constraints (max cost, max latency, etc.)

    The router uses this to answer:
    - Which providers can handle this request?
    - Which provider best matches the user's constraints?
    - Which provider gives the best balance of cost/quality/speed?
    """

    request: LLMRequest
    available_providers: List[str]
    provider_metrics: Dict[str, ProviderMetrics]
    constraints: Dict[str, Any] = field(default_factory=dict)
